sudo: false

language: php

php:
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

matrix:
    include:
    - php: "5.4"
      env: WP_VERSION=4.0
    - php: "5.4"
      env: WP_VERSION=4.1
    - php: "7.0"
      env: WP_VERSION=4.4

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit && phpunit --group ajax
